package software.aoc.day07.a;

import org.junit.Test;

import java.io.IOException;
import java.io.InputStream;

import static org.assertj.core.api.Assertions.assertThat;

public class TachyonManifoldTest {

    String tachyon_map = """
            .......S.......
            ...............
            .......^.......
            ...............
            ......^.^......
            ...............
            .....^.^.^.....
            ...............
            ....^.^...^....
            ...............
            ...^.^...^.^...
            ...............
            ..^...^.....^..
            ...............
            .^.^.^.^.^...^.
            ...............
            """;

    @Test
    public void given_tachyon_map_should_account_beam_propagation() {
        assertThat(TachyonManifold.with("""
                                             ...S...
                                             ...^...
                                             ..^...^
                                             .^..^..
                                             .......
                                             """).extend()).isEqualTo(new int[] {83, 46, 83, 83, 46, 83, 46});
        assertThat(TachyonManifold.with(tachyon_map).extend()).isEqualTo(new int[] {83, 46, 83, 46, 83, 46, 83, 46, 83, 46, 83, 83, 83, 46, 83});
    }

    @Test
    public void given_tachyon_map_should_account_number_of_split_beams() {
        assertThat(TachyonManifold.with("""
                                             ...S...
                                             ...^...
                                             ..^...^
                                             .^..^..
                                             .......
                                             """).countSplitBeams()).isEqualTo(4);
        assertThat(TachyonManifold.with(tachyon_map).countSplitBeams()).isEqualTo(21);
    }

    @Test
    public void reward() throws IOException {
        try (InputStream inputStream = TachyonManifoldTest.class.getResourceAsStream("/day07/input_aoc7.txt")) {
            assertThat(TachyonManifold.with(new String(inputStream.readAllBytes())).countSplitBeams()).isEqualTo(1587);
        }
    }
}
